# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{eppit}
  s.version = "0.8.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["vihai"]
  s.date = %q{2011-01-04}
  s.description = %q{EPP over HTTPS protocol implementation developed for NIC.it}
  s.email = %q{daniele@orlandi.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "VERSION",
    "lib/eppit.rb",
    "lib/eppit/exceptions.rb",
    "lib/eppit/interface.rb",
    "lib/eppit/session.rb",
    "lib/eppit/xml_interface.rb",
    "lib/require_parameters.rb"
  ]
  s.homepage = %q{http://www.yggdra.it/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{EPP over HTTPS implementation for NIC.it}
  s.test_files = [
    "spec/eppit_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<vihai-roxml>, [">= 3.1.5"])
      s.add_development_dependency(%q<rspec>, [">= 2.1.0"])
    else
      s.add_dependency(%q<vihai-roxml>, [">= 3.1.5"])
      s.add_dependency(%q<rspec>, [">= 2.1.0"])
    end
  else
    s.add_dependency(%q<vihai-roxml>, [">= 3.1.5"])
    s.add_dependency(%q<rspec>, [">= 2.1.0"])
  end
end

